name: publishpypi

on:
  push:
    branches:
      - "main"
    tags:
      - '**'
    paths:
      - 'castoredc_api/client/**'
      - 'castoredc_api/study/**'
      - 'castoredc_api/importer/**'
      - 'setup.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Preparation - Setup Environment
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Preparation - Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build and publish to pypi (test)
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi --verbose dist/*

    - name: Publish to pypi (production)
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload --verbose dist/*